theme: jekyll-theme-minimal
title: Welcome to Tony Shelton's Home Page!
description: Feel free to return to my page at any time for updates.
[My Code Journal](http://www.tonyshelton.com/code_journal/)
[My Artwork](http://www.tonysheltonart.com)
